import type {
  Opportunity,
  Booking,
  Sponsorship,
  SponsorshipRequest,
  KnowledgeBaseEntry,
  ImpactMetrics,
  LearnerProfileData,
  ProviderProfileData,
} from '../types';

export const MOCK_LEARNER: LearnerProfileData = {
  id: 'learner-101',
  user_id: 'usr-learner-1',
  full_name: 'Kamal Perera',
  education_level: 'G.C.E. A/L (Physical Science & ICT)',
  field_of_interest: 'Information & Communication Technology, Software Engineering',
  preferred_language: 'English / Sinhala',
  budget_max: 15000,
  location: 'Colombo, Western Province',
  bio: 'A/L student passionate about python coding, cloud computing, and AI application development.',
};

export const MOCK_PROVIDERS: ProviderProfileData[] = [
  {
    id: 'prov-1',
    user_id: 'usr-prov-1',
    organization_name: 'DevAcademy Sri Lanka',
    bio: 'Premier technology institute providing hands-on coding bootcamps and A/L ICT acceleration.',
    website_url: 'https://devacademy.lk',
    verification_status: 'verified',
    rating: 4.9,
    total_students: 1240,
    sessions_completed: 185,
  },
  {
    id: 'prov-2',
    user_id: 'usr-prov-2',
    organization_name: 'Dr. Nimal Senanayake',
    bio: 'Senior University Lecturer in Computer Science with 12+ years teaching experience.',
    website_url: 'https://nimalcodes.com',
    verification_status: 'verified',
    rating: 4.8,
    total_students: 450,
    sessions_completed: 62,
  },
  {
    id: 'prov-3',
    user_id: 'usr-prov-3',
    organization_name: 'FutureTech Mentors',
    bio: 'Community of industry software engineers offering 1-on-1 career coaching and mock interviews.',
    website_url: 'https://futuretechmentors.org',
    verification_status: 'pending',
    rating: 4.6,
    total_students: 120,
    sessions_completed: 24,
  },
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    provider_id: 'prov-1',
    provider_name: 'DevAcademy Sri Lanka',
    provider_verified: true,
    title: 'A/L ICT Python & SQL Fast-Track Bootcamp',
    type: 'COURSE',
    description: 'Comprehensive 6-week online masterclass covering Python fundamentals, database design, and SQL queries tailored for the A/L ICT syllabus with exam-oriented practical exercises.',
    subject: 'ICT',
    target_level: 'A/L Students',
    price: 8500,
    delivery_mode: 'online',
    location: 'Online via Zoom',
    duration: '6 Weeks (12 Sessions)',
    status: 'active',
    match_score: 0.94,
    match_reasons: ['Exact match for A/L ICT syllabus', 'Fits budget under LKR 15,000', 'Highly rated verified provider'],
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'opp-2',
    provider_id: 'prov-2',
    provider_name: 'Dr. Nimal Senanayake',
    provider_verified: true,
    title: '1-on-1 Data Structures & Algorithms Tutoring',
    type: 'TUITION',
    description: 'Personalized 1-on-1 coaching for computer science undergraduate aspirants focusing on algorithmic problem solving, sorting algorithms, and memory management.',
    subject: 'Computer Science',
    target_level: 'Beginner to Intermediate',
    price: 12000,
    delivery_mode: 'online',
    location: 'Google Meet',
    duration: '4 Sessions (1h each)',
    status: 'active',
    match_score: 0.89,
    match_reasons: ['Strong alignment with Software Engineering interests', 'Direct lecturer mentorship'],
    created_at: '2026-08-03T14:30:00Z',
  },
  {
    id: 'opp-3',
    provider_id: 'prov-1',
    provider_name: 'DevAcademy Sri Lanka',
    provider_verified: true,
    title: 'Full Stack Web Development Workshop: React & Supabase',
    type: 'WORKSHOP',
    description: 'Weekend hands-on hackathon workshop building modern web apps with React, Tailwind CSS, and Supabase backend. Includes certificate of completion.',
    subject: 'Web Development',
    target_level: 'Open to All',
    price: 0,
    delivery_mode: 'online',
    location: 'Online (YouTube Live + Discord)',
    duration: '2 Days (Saturday & Sunday)',
    status: 'active',
    match_score: 0.96,
    match_reasons: ['Free sponsored workshop', 'Includes hands-on practical project'],
    created_at: '2026-08-05T09:15:00Z',
  },
  {
    id: 'opp-4',
    provider_id: 'prov-3',
    provider_name: 'FutureTech Mentors',
    provider_verified: false,
    title: 'Software Engineer Internship Mock Interview & Resume Audit',
    type: 'MOCK_INTERVIEW',
    description: 'Simulated 45-minute technical interview with a Senior SE followed by 15-minute resume feedback and portfolio review.',
    subject: 'Career Development',
    target_level: 'Undergraduates / Job Seekers',
    price: 5000,
    delivery_mode: 'online',
    location: 'Google Meet',
    duration: '1 Hour',
    status: 'active',
    match_score: 0.82,
    match_reasons: ['Prepares for industry entry', 'Affordable single session'],
    created_at: '2026-08-08T11:00:00Z',
  },
  {
    id: 'opp-5',
    provider_id: 'prov-2',
    provider_name: 'Dr. Nimal Senanayake',
    provider_verified: true,
    title: 'AI & Machine Learning Foundations for School Leavers',
    type: 'COURSE',
    description: 'Introduction to Artificial Intelligence, linear algebra concepts, neural networks, and building simple ML predictors with scikit-learn.',
    subject: 'Artificial Intelligence',
    target_level: 'School Leavers / Beginners',
    price: 15000,
    delivery_mode: 'in-person',
    location: 'DevSpace Center, Colombo 03',
    duration: '4 Weeks (Saturdays)',
    status: 'active',
    match_score: 0.88,
    match_reasons: ['Matches AI interest', 'In-person lab access'],
    created_at: '2026-08-09T16:20:00Z',
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-1',
    opportunity_id: 'opp-3',
    opportunity_title: 'Full Stack Web Development Workshop: React & Supabase',
    opportunity_type: 'WORKSHOP',
    provider_id: 'prov-1',
    provider_name: 'DevAcademy Sri Lanka',
    learner_id: 'learner-101',
    learner_name: 'Kamal Perera',
    status: 'accepted',
    price: 0,
    date: '2026-08-20T09:00:00Z',
    created_at: '2026-08-10T12:00:00Z',
  },
  {
    id: 'bk-2',
    opportunity_id: 'opp-1',
    opportunity_title: 'A/L ICT Python & SQL Fast-Track Bootcamp',
    opportunity_type: 'COURSE',
    provider_id: 'prov-1',
    provider_name: 'DevAcademy Sri Lanka',
    learner_id: 'learner-101',
    learner_name: 'Kamal Perera',
    status: 'pending',
    price: 8500,
    date: '2026-08-25T17:00:00Z',
    created_at: '2026-08-11T15:30:00Z',
  },
];

export const MOCK_SPONSORSHIPS: Sponsorship[] = [
  {
    id: 'sp-1',
    sponsor_id: 'spon-1',
    sponsor_name: 'SLASSCOM Educational Fund',
    learner_id: 'learner-101',
    learner_name: 'Kamal Perera',
    opportunity_id: 'opp-1',
    opportunity_title: 'A/L ICT Python & SQL Fast-Track Bootcamp',
    amount: 8500,
    status: 'pending',
    note: 'Sponsorship pledged for high-achieving student in Colombo North district.',
    created_at: '2026-08-06T14:00:00Z',
  },
  {
    id: 'sp-2',
    sponsor_id: 'spon-2',
    sponsor_name: 'Global Tech Foundation',
    learner_id: 'learner-102',
    learner_name: 'Dilini Rathnayake',
    opportunity_id: 'opp-5',
    opportunity_title: 'AI & Machine Learning Foundations for School Leavers',
    amount: 15000,
    status: 'completed',
    note: 'Fully funded scholarship for female tech lead in STEM.',
    created_at: '2026-08-02T11:20:00Z',
  },
];

export const MOCK_SPONSORSHIP_REQUESTS: SponsorshipRequest[] = [
  {
    id: 'req-1',
    learner_id: 'learner-101',
    learner_name: 'Kamal Perera',
    education_level: 'G.C.E. A/L ICT Student',
    title: 'Financial support for A/L ICT Exam Prep & Cloud Infrastructure Course',
    reason: 'I am preparing for A/L ICT while supporting my family. I need assistance funding the fast-track coding bootcamp to qualify for university computer science entrance.',
    amount_needed: 8500,
    amount_raised: 4250,
    created_at: '2026-08-05T08:00:00Z',
  },
  {
    id: 'req-2',
    learner_id: 'learner-103',
    learner_name: 'Sahan Wickramasinghe',
    education_level: 'Undergraduate (Year 1 CS)',
    title: 'Sponsorship for AWS Certified Cloud Practitioner Exam & Courseware',
    reason: 'Passionate about cloud architecture but lack funds for international certification exam voucher.',
    amount_needed: 25000,
    amount_raised: 15000,
    created_at: '2026-08-07T10:30:00Z',
  },
];

export const MOCK_KNOWLEDGE_BASE: KnowledgeBaseEntry[] = [
  {
    id: 'kb-1',
    category: 'scholarship',
    title: 'Government Higher Education IT Scholarship Scheme 2026',
    content: 'Full and partial tuition waivers for G.C.E. A/L students scoring 3 Passes in Physical Science or Commerce with ICT, entering accredited software engineering programs.',
    source_url: 'https://mohe.gov.lk/scholarships-2026',
    status: 'verified',
    created_at: '2026-07-15T09:00:00Z',
  },
  {
    id: 'kb-2',
    category: 'internship',
    title: 'National Software Industry Apprentice Internship Program',
    content: '6-month paid industrial placements for ICT school leavers and diploma holders with LKR 35,000 monthly stipend at top software houses.',
    source_url: 'https://slasscom.lk/internships',
    status: 'verified',
    created_at: '2026-07-20T11:00:00Z',
  },
  {
    id: 'kb-3',
    category: 'course',
    title: 'Open University Free Foundational Computer Science Modules',
    content: 'Self-paced online introductory modules covering Programming in Python, Web Basics, and Database Management open to all Sri Lankan citizens without entry prerequisites.',
    source_url: 'https://ou.ac.lk/free-cs-courses',
    status: 'verified',
    created_at: '2026-07-28T14:15:00Z',
  },
  {
    id: 'kb-4',
    category: 'competition',
    title: 'National Youth AI & Hackathon Challenge 2026',
    content: 'Annual national innovation competition for school and university students to build AI solutions targeting education, healthcare, and agriculture. LKR 1M total prize pool.',
    source_url: 'https://hackathon.gov.lk',
    status: 'verified',
    created_at: '2026-08-01T16:00:00Z',
  },
  {
    id: 'kb-5',
    category: 'workshop',
    title: 'Free Cybersecurity & Ethical Hacking Awareness Weekend',
    content: 'Interactive virtual lab session explaining web application vulnerabilities, network security, and defensive security tools.',
    source_url: 'https://cybersec.lk/free-workshop',
    status: 'draft',
    created_at: '2026-08-10T18:00:00Z',
  },
];

export const MOCK_IMPACT_METRICS: ImpactMetrics = {
  active_providers: 18,
  learners_supported: 1420,
  total_bookings: 385,
  sponsored_learners: 42,
  sponsorship_amount: 575000, // LKR
  opportunities_count: 26,
};
